In [1]:
import pandas as pd

In [2]:
original_data = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/Olympics-Dataset/refs/heads/master/athletes/bios.csv")
original_data.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df = original_data.copy()
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

### Sex	Column
[1] make sure all the Sex column has the values of Male or Female
[2] count the null values

### Used name Column
[1] change the name of the Used name column to Name
[2] make sure all the names is not Null
[3] make sure all the names has • in it
[4] remove the • from it

### Born Column
[1] make sure that all the columns has the word "in" in them
[2] replace the "in" and "(" with "," and the ")" with ""
[3] split the column into Born date, Born city, Born region, Born country
[4] count the None values in Born date, Born city, Born region and Born country
[5] turn the Born date into datetime type

### Died Column
[1] make sure that all the columns has the word "in" in them
[2] replace the "in" and "(" with "," and the ")" with ""
[3] split the column into Died date, Died city, Died region, Died country
[4] turn the Died date into datetime type

### athlete_id Column
[1] make sure that all the values in the column are not null

### Measurements Column
[1] split the column into Height_cm and Weight_kg
[2] put the values in the Height_cm which has kg in it into Weight_kg and then remove it from Height_cm

### Sex	Column
[1] make sure all the Sex column has the values of Male or Female

In [55]:
df["Sex"].unique()

array(['Male', 'Female'], dtype=object)

[2] count the null values

In [56]:
df["Sex"].isnull().sum()

np.int64(0)

### Used name Column
[1] change the name of the Used name column to Name

In [57]:
df = df.rename(columns={"Used name":"Name"})
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[2] make sure all the names is not Null

In [58]:
df["Name"].isnull().sum()

np.int64(0)

[3] make sure all the names has • in it and remove the • from it

In [59]:
df["Name"] = df["Name"].str.replace("•", " ")
df["Name"].head()

0    Jean-François Blanchy
1           Arnaud Boetsch
2             Jean Borotra
3          Jacques Brugnon
4             Albert Canet
Name: Name, dtype: object

### Born Column

In [60]:
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[1] make sure that all the columns has the word "in" in them

In [61]:
# number of records that do not have "in" in it without Null values --> 22820
df[~df["Born"].str.contains("in", na=True)]["Born"].count()

np.int64(22820)

In [62]:
# number of records that do not have "in" in it with Null values --> 24548
len(df[~df["Born"].str.contains("in", na=False)]["Born"])

24548

In [63]:
Born_Pattern = r"(\d+ \w+ \d+)"
len(df[~df["Born"].str.contains("in", na=True) & ~df["Born"].str.match(Born_Pattern, na=True)])
len(df[~df["Born"].str.contains("in", na=True) & ~df["Born"].str.match(Born_Pattern, na=True)])

1161

[2] replace the "in" and "(" with "," and the ")" with ""

In [64]:
df["Born"] = df["Born"].str.replace("in", ",", n=1)
df["Born"] = df["Born"].str.replace("(", ",")
df["Born"] = df["Born"].str.replace(")", "")

df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[3] split the column into Born date, Born city, Born region, Born country

In [65]:
df[["Born date", "Born city", "Born region", "Born country"]] = df["Born"].str.split(",", n=3, expand=True)
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12 December 1886,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1 April 1969,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,13 August 1898,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,11 May 1895,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,17 April 1878,Wandsworth,England,GBR

In [67]:
import numpy as np
df["Born date"] = df["Born date"].replace("", np.nan)

In [66]:
new_born_date_pattern = r"(\D+ \W+ \D+)"
df[~df["Born date"].str.match(new_born_date_pattern, na=True) & ~df["Born date"].str.match(r"(\d)", na=True)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
1251,Competed in Olympic Games,Male,Eduardo•Cornejo Díaz,Eduardo Cornejo,",c. 1929","23 November 1998 in Santiago, Santiago Metropo...",Chile,1258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,c. 1929,None,None
1277,Competed in Olympic Games,Male,Manuel•Videla Castillo,Manuel Videla,",circa 1920",NaN,Chile,1284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,circa 1920,None,None
1794,Competed in Olympic Games,Male,Luis•Castillo Sánchez,Luis Castillo,", Guayaquil, Guayas ,ECU",NaN,Ecuador,1801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,Guayaquil,Guayas,ECU
1800,Competed in Olympic Games,Male,Lincoln•Salcedo Reina,Lincoln Salcedo,", Guayaquil, Guayas ,ECU",NaN,Ecuador,1807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,Guayaquil,Guayas,ECU
1805,Competed in Olympic Games,Male,Gharib Ibrahim•Afifi,Gharib Afifi,", Al-Qahira ,Cairo, Al-Qahira ,EGY",(In the 1990s),Egypt,1812,NaN,"El-Olympi, Al-Iskanderiya (EGY)",NaN,NaN,NaN,NaN,غريب ابراهيم•عفيفي,NaN,,Al-Qahira,Cairo,"Al-Qahira ,EGY"

In [46]:
df["Born date"] = pd.to_datetime(df["Born date"], errors="coerce")
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-12-12,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1969-04-01,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,1895-05-11,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1878-04-17,Wandsworth,England,GBR

In [129]:
len(df[df["Born city"].str.match(r"\w+ \d+", na=False)]) # 50
df[df["Born city"].str.match(r"\w+ \d+", na=False)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
1277,Competed in Olympic Games,Male,Manuel•Videla Castillo,Manuel Videla,",circa 1920",NaN,Chile,1284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1920,circa 1920,None,None
3865,Competed in Olympic Games,Male,"Babu ""Bob""•Lall",Bob Lall,",circa 1924","16 May 1953 in Kolkata (Calcutta), West Bengal...",India,3878,NaN,"?, Bengal (IND)",NaN,NaN,Bob Lal,NaN,NaN,NaN,1924,circa 1924,None,None
4946,Competed in Olympic Games,Male,Manuel Eugenio•López,Manuel López,",circa 1929","9 April 1954 in Córdoba, Córdoba (ARG)",Argentina,4964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1929,circa 1929,None,None
5843,Competed in Olympic Games,Male,Chien•Kok-Ching,Chien Kok-Ching,",circa 1934",NaN,Chinese Taipei,5866,NaN,NaN,NaN,NaN,NaN,NaN,錢•國楨,Oriental,1934,circa 1934,None,None
5846,Competed in Olympic Games,Male,Visit•Chaicharoen,Visit Chaicharoen,",circa 1933",NaN,Thailand,5869,NaN,NaN,NaN,NaN,Visit Chivacharern,NaN,วิสิตย์•ชัยเจริญ,NaN,1933,circa 1933,None,None

In [ ]:
# fill the NON values in the Born date column which has it's date in the Born city (c. |  circa)
df["Born date"] = df["Born date"].fillna(df[df["Born city"].str.match(r"(\w+)", na=False)]["Born city"].str.extract(r"(\d+)").squeeze())

In [132]:
df.loc[df["Born city"].str.contains("c.", na=False), "Born city"] = None
df.loc[df["Born city"].str.contains("circa", na=False), "Born city"] = None

In [133]:
len(df[df["Born city"].str.match(r"\w+", na=False)]) # 53
df[df["Born city"].str.match(r"\w+", na=False)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
15784,Competed in Olympic Games,Male,"Rohinton Rustomji ""R. R.""•Noble",R. R. Noble,",1926 or 1927",17 June 1975 in ? (IND),India,15895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1926,1926 or 1927,None,None

In [68]:
# replacing the ? with None vlaues in Born city
df["Born city"] = df["Born city"].replace("?", np.nan)

In [69]:
born_city_pattern = r"(\W+)"
df[~df["Born city"].str.match(born_city_pattern, na=True)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
1251,Competed in Olympic Games,Male,Eduardo•Cornejo Díaz,Eduardo Cornejo,",c. 1929","23 November 1998 in Santiago, Santiago Metropo...",Chile,1258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c. 1929,None,None
1277,Competed in Olympic Games,Male,Manuel•Videla Castillo,Manuel Videla,",circa 1920",NaN,Chile,1284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,circa 1920,None,None
3865,Competed in Olympic Games,Male,"Babu ""Bob""•Lall",Bob Lall,",circa 1924","16 May 1953 in Kolkata (Calcutta), West Bengal...",India,3878,NaN,"?, Bengal (IND)",NaN,NaN,Bob Lal,NaN,NaN,NaN,NaN,circa 1924,None,None
4570,Competed in Olympic Games,Male,Manuel•Ponce,Manuel Ponce,",c. 1915",June 1935,Mexico,4586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c. 1915,None,None
4946,Competed in Olympic Games,Male,Manuel Eugenio•López,Manuel López,",circa 1929","9 April 1954 in Córdoba, Córdoba (ARG)",Argentina,4964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,circa 1929,None,None