In [1]:
import pandas as pd

In [2]:
original_data = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/Olympics-Dataset/refs/heads/master/athletes/bios.csv")
original_data.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
df = original_data.copy()
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

### Sex	Column
[1] make sure all the Sex column has the values of Male or Female
[2] count the null values

### Used name Column
[1] change the name of the Used name column to Name
[2] make sure all the names is not Null
[3] make sure all the names has • in it
[4] remove the • from it

### Born Column
[1] make sure that all the columns has the word "in" in them
[2] replace the "in" and "(" with "," and the ")" with ""
[3] split the column into Born date, Born city, Born region, Born country
[4] count the None values in Born date, Born city, Born region and Born country
[5] turn the Born date into datetime type

### Died Column
[1] make sure that all the columns has the word "in" in them
[2] replace the "in" and "(" with "," and the ")" with ""
[3] split the column into Died date, Died city, Died region, Died country
[4] turn the Died date into datetime type

### athlete_id Column
[1] make sure that all the values in the column are not null

### Measurements Column
[1] split the column into Height_cm and Weight_kg
[2] put the values in the Height_cm which has kg in it into Weight_kg and then remove it from Height_cm

### Sex	Column
[1] make sure all the Sex column has the values of Male or Female

In [66]:
df["Sex"].unique()

array(['Male', 'Female'], dtype=object)

[2] count the null values

In [67]:
df["Sex"].isnull().sum()

np.int64(0)

### Used name Column
[1] change the name of the Used name column to Name

In [68]:
df = df.rename(columns={"Used name":"Name"})
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[2] make sure all the names is not Null

In [69]:
df["Name"].isnull().sum()

np.int64(0)

[3] make sure all the names has • in it and remove the • from it

In [70]:
df["Name"] = df["Name"].str.replace("•", " ")
df["Name"].head()

0    Jean-François Blanchy
1           Arnaud Boetsch
2             Jean Borotra
3          Jacques Brugnon
4             Albert Canet
Name: Name, dtype: object

### Born Column

In [71]:
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[1] make sure that all the columns has the word "in" in them

In [72]:
# number of records that do not have "in" in it without Null values --> 22820
df[~df["Born"].str.contains("in", na=True)]["Born"].count()

np.int64(22820)

In [73]:
# number of records that do not have "in" in it with Null values --> 24548
len(df[~df["Born"].str.contains("in", na=False)]["Born"])

24548

In [74]:
Born_Pattern = r"(\d+ \w+ \d+)"
len(df[~df["Born"].str.contains("in", na=True) & ~df["Born"].str.match(Born_Pattern, na=True)])
len(df[~df["Born"].str.contains("in", na=True) & ~df["Born"].str.match(Born_Pattern, na=True)])

1161

[2] replace the "in" and "(" with "," and the ")" with ""

In [75]:
df["Born"] = df["Born"].str.replace("in", ",", n=1)
df["Born"] = df["Born"].str.replace("(", ",")
df["Born"] = df["Born"].str.replace(")", "")

df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[3] split the column into Born date, Born city, Born region, Born country

In [76]:
df[["Born date", "Born city", "Born region", "Born country"]] = df["Born"].str.split(",", n=3, expand=True)
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12 December 1886,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1 April 1969,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,13 August 1898,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,11 May 1895,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,17 April 1878,Wandsworth,England,GBR

In [77]:
import numpy as np
df["Born date"] = df["Born date"].replace("", np.nan)

In [78]:
new_born_date_pattern = r"(\D+ \W+ \D+)"
df[~df["Born date"].str.match(new_born_date_pattern, na=True) & ~df["Born date"].str.match(r"(\d)", na=True)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
2209,Competed in Olympic Games,Female,"Lenora Josephine ""Leonie""•Taylor",Leonie Taylor,"March 1870 , Cincinnati, Ohio ,USA","9 March 1936 in Mount Sterling, Kentucky (USA)",United States,2219,NaN,"Cincinnati Archers, Cincinnati (USA)",NaN,NaN,NaN,NaN,NaN,NaN,March 1870,Cincinnati,Ohio,USA
2218,Competed in Olympic Games,Male,William Allen•Clark,William Clark,"March 1842 , Cincinnati, Ohio ,USA","20 October 1913 in Knoxville, Tennessee (USA)",United States,2228,NaN,"Cincinnati Archers, Cincinnati (USA)",NaN,NaN,NaN,NaN,NaN,NaN,March 1842,Cincinnati,Ohio,USA
2222,Competed in Olympic Games,Male,Edward Williston•Frentz,Edward Frentz,"May 1863 , ?, Maine ,USA","28 August 1943 in Melrose, Massachusetts (USA)",United States,2232,NaN,"Boston Archery Club, Boston (USA)",NaN,NaN,NaN,NaN,NaN,NaN,May 1863,?,Maine,USA
2744,Competed in Olympic Games,Male,Andrew I.•Drew,Andrew Drew,"February 1885 , ?, Missouri ,USA","12 June 1913 in Bath Township, Ohio (USA)",United States,2756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,February 1885,?,Missouri,USA
8032,Competed in Olympic Games,Male,"Alexander Indrajith ""Alex""•Obeysekera (Obeysek...",Alex Obeysekera,"March 1918 , Colombo, Basnahira ,SRI","28 April 2002 in Colombo, Basnahira (SRI)",Sri Lanka,8074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March 1918,Colombo,Basnahira,SRI

In [79]:
len(df[df["Born city"].str.match(r"\w+ \d+", na=False)]) # 50
df[df["Born city"].str.match(r"\w+ \d+", na=False)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
1277,Competed in Olympic Games,Male,Manuel•Videla Castillo,Manuel Videla,",circa 1920",NaN,Chile,1284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,circa 1920,None,None
3865,Competed in Olympic Games,Male,"Babu ""Bob""•Lall",Bob Lall,",circa 1924","16 May 1953 in Kolkata (Calcutta), West Bengal...",India,3878,NaN,"?, Bengal (IND)",NaN,NaN,Bob Lal,NaN,NaN,NaN,NaN,circa 1924,None,None
4946,Competed in Olympic Games,Male,Manuel Eugenio•López,Manuel López,",circa 1929","9 April 1954 in Córdoba, Córdoba (ARG)",Argentina,4964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,circa 1929,None,None
5843,Competed in Olympic Games,Male,Chien•Kok-Ching,Chien Kok-Ching,",circa 1934",NaN,Chinese Taipei,5866,NaN,NaN,NaN,NaN,NaN,NaN,錢•國楨,Oriental,NaN,circa 1934,None,None
5846,Competed in Olympic Games,Male,Visit•Chaicharoen,Visit Chaicharoen,",circa 1933",NaN,Thailand,5869,NaN,NaN,NaN,NaN,Visit Chivacharern,NaN,วิสิตย์•ชัยเจริญ,NaN,NaN,circa 1933,None,None

In [80]:
# fill the NON values in the Born date column which has it's date in the Born city (c. |  circa)
df["Born date"] = df["Born date"].fillna(df[df["Born city"].str.match(r"(\w+)", na=False)]["Born city"].str.extract(r"(\d+)").squeeze())

In [81]:
df.loc[df["Born city"].str.contains("c.", na=False), "Born city"] = None
df.loc[df["Born city"].str.contains("circa", na=False), "Born city"] = None
df.loc[df["Born city"].str.contains("1926 or 1927", na=False), "Born city"] = None

In [82]:
len(df[df["Born city"].str.match(r"\w+", na=False)]) # 53
df[df["Born city"].str.match(r"\w+", na=False)].head()

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

In [83]:
df["Born date"] = pd.to_datetime(df["Born date"], errors="coerce")
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-12-12,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1969-04-01,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,1895-05-11,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1878-04-17,Wandsworth,England,GBR

### Born city

In [84]:
# replacing the ? with None vlaues in Born city
df["Born city"] = df["Born city"].replace("?", np.nan)

In [85]:
born_city_pattern = r"(\W+)"
df[~df["Born city"].str.match(born_city_pattern, na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

In [86]:
df[df["Born city"].str.contains(",", na=False)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

### Born region

In [87]:
df[df["Born region"].str.contains("-", na=False)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA
16,Competed in Olympic Games • Competed in Olympi...,Male,Guy•Forget,Guy Forget,"4 January 1965 , Casablanca, Casablanca-Settat...",NaN,France,17,189 cm / 79 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1965-01-04,None,Casablanca-Settat,MAR
24,Competed in Olympic Games,Male,Paul Émile•Lecaron,Paul Lecaron,"29 July 1863 , Neuilly-sur-Seine, Hauts-de-Sei...","17 September 1940 in Paris XVIe, Paris (FRA)",France,25,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1863-07-29,Neuilly-sur-Seine,Hauts-de-Seine,FRA
25,Competed in Olympic Games,Male,Henri•Leconte,Henri Leconte,"4 July 1963 , Lillers, Pas-de-Calais ,FRA",NaN,France,26,184 cm / 78 kg,LTC Nice,Le vengeur masqué,NaN,NaN,NaN,NaN,NaN,1963-07-04,Lillers,Pas-de-Calais,FRA
71,Competed in Olympic Games,Female,Clare Jacqueline•Wood,Clare Wood,"8 March 1968 , Zululand, KwaZulu-Natal ,RSA",NaN,Great Britain,72,175 cm / 65 kg,Southdown Lawn Tennis Club,NaN,NaN,NaN,NaN,NaN,NaN,1968-03-08,Zululand,KwaZulu-Natal,RSA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145325,Competed in Olympic Games,Female,Lidiya•Hunko,Lidiya Hunko,"10 August 1993 , Ivano-Frankivsk, Ivano-Franki...",NaN,Ukraine,149047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993-08-10,Ivano-Frankivsk,Ivano-Frankivsk,UKR
145464,Competed in Olympic Games,Male,Joonas Aleksanteri•Nättinen,Joonas Nättinen,"3 January 1991 , Jämsä, Keski-Suomi ,FIN",NaN,Finland,149191,189 cm / 90 kg,"Severstal Cherepovets, Cherepovets (RUS)",NaN,NaN,NaN,NaN,NaN,NaN,1991-01-03,Jämsä,Keski-Suomi,FIN
145467,Competed in Olympic Games,Female,Elisa Maria•Nakab,Elisa Nakab,"8 May 1998 , Briançon, Hautes-Alpes ,FRA",NaN,Italy,149194,NaN,Sporting Club Livigno,NaN,NaN,NaN,NaN,NaN,NaN,1998-05-08,Briançon,Hautes-Alpes,FRA
145488,Competed in Olympic Games,Male,Shakeel•John,Shakeel John,"30 July 2001 , Mount Hope, Tunapuna-Piarco ,TTO",NaN,Trinidad and Tobago,149215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-07-30,Mount Hope,Tunapuna-Piarco,TTO
145498,Competed in Olympic Games,Male,André•Foussard,André Foussard,"19 May 1899 , Niort, Deux-Sèvres ,FRA","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1899-05-19,Niort,Deux-Sèvres,FRA

In [88]:
born_region_pattern = r"(\d+)"
df[df["Born region"].str.match(born_region_pattern, na=False)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

In [89]:
born_region_pattern = r"(\w+)"
df[~df["Born region"].str.match(born_region_pattern, na=True)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-12-12,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1969-04-01,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,1895-05-11,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1878-04-17,Wandsworth,England,GBR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George Wright,"21 July 1890 , Toronto, Ontario ,CAN","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,1890-07-21,Toronto,Ontario,CAN
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina Luchnikova,"30 January 2002 , Serov, Sverdlovsk ,RUS",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,NaN,NaN,2002-01-30,Serov,Sverdlovsk,RUS
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya Smirnova,"8 May 1998 , Kotlas, Arkhangelsk ,RUS",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,Юлия•Смирнова,NaN,1998-05-08,Kotlas,Arkhangelsk,RUS
145498,Competed in Olympic Games,Male,André•Foussard,André Foussard,"19 May 1899 , Niort, Deux-Sèvres ,FRA","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1899-05-19,Niort,Deux-Sèvres,FRA
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill Phillips,"15 July 1913 , Dulwich Hill, New South Wales ,AUS","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1913-07-15,None,New South Wales,AUS

### Born country

In [90]:
born_city_pattern = r"(\w+)"
df[~df["Born country"].str.match(born_city_pattern, na=True)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
49,Competed in Olympic Games,Female,Gillian Carol•Gowers,Gillian Gowers,"9 April 1964 , Horfield, Clifton, England ,GBR",NaN,Great Britain,50,157 cm / 55 kg,Gosling,NaN,NaN,NaN,NaN,NaN,NaN,1964-04-09,Horfield,Clifton,"England ,GBR"
80,Competed in Olympic Games,Male,George Aristides•Caridia (Karidias-),George Caridia,"20 February 1869 , Kolkata ,Calcutta, West Ben...","21 April 1937 in Marylebone, England (GBR)",Great Britain,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1869-02-20,Kolkata,Calcutta,"West Bengal ,IND"
101,Competed in Olympic Games,Male,Algernon Robert Fitzhardinge•Kingscote,Algernon Kingscote,"3 February 1888 , Bengaluru ,Bangalore, Karnat...","21 December 1964 in Woking, England (GBR)",Great Britain,102,NaN,NaN,Algy,NaN,NaN,NaN,NaN,NaN,1888-02-03,Bengaluru,Bangalore,"Karnataka ,IND"
103,Competed in Olympic Games,Male,Arthur Holden•Lowe,Arthur Lowe,"29 January 1886 , Edgbaston, Birmingham, Engla...","22 October 1958 in London, England (GBR)",Great Britain,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-01-29,Edgbaston,Birmingham,"England ,GBR"
104,Competed in Olympic Games,Male,Francis Gordon•Lowe,Gordon Lowe,"21 June 1884 , Edgbaston, Birmingham, England ...","17 May 1972 in London, England (GBR)",Great Britain,105,NaN,NaN,NaN,2nd Baronet of Lowe,NaN,NaN,NaN,NaN,1884-06-21,Edgbaston,Birmingham,"England ,GBR"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145450,Competed in Olympic Games,Female,Anna Stanislavovna•Shcherbakova,Anna Shcherbakova,"28 March 2004 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149174,NaN,NaN,NaN,NaN,NaN,NaN,Анна Станиславовна•Щербакова,NaN,2004-03-28,Moskva,Moscow,"Moskva ,RUS"
145465,Competed in Olympic Games,Male,Stanislav Sergeyevich•Galiyev,Stanislav Galiyev,"17 January 1992 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149192,188 cm / 82 kg,"Dynamo Moskva, Moskva (RUS)",NaN,NaN,NaN,NaN,Станислав Сергеевич•Галиев,NaN,1992-01-17,Moskva,Moscow,"Moskva ,RUS"
145487,Competed in Olympic Games,Female,Yekaterina Aleksandrovna•Kosova,Yekaterina Kosova,"25 April 1996 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149214,NaN,NaN,NaN,NaN,NaN,NaN,Екатерина Александровна•Косова,NaN,1996-04-25,Moskva,Moscow,"Moskva ,RUS"
145492,Competed in Olympic Games,Male,Carlos•García-Ordóñez Montalvo,Carlos García-Ordóñez,"24 April 1927 , La Habana ,Havana, Ciudad de L...","24 November 2019 in Miami, Florida (USA)",Cuba,149219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1927-04-24,La Habana,Havana,"Ciudad de La Habana ,CUB"
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya Merkusheva,"20 September 1999 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Валерия Сергеевна•Меркушева,NaN,1999-09-20,Moskva,Moscow,"Moskva ,RUS"

In [91]:
df["Born country"] = df[df["Born country"].str.contains(",", na=False)]["Born country"].str.extract(r",(\w+)").squeeze()

In [92]:
born_city_pattern = r"(\w+)"
df[~df["Born country"].str.match(born_city_pattern, na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

### Died Column
[1] make sure that all the columns has the word "in" in them

In [93]:
# number of records that contain "in" without the None values
len(df[df["Died"].str.contains("in", na=False)])    # 28878

28878

In [94]:
# number of records that do not contain "in"
len(df[~df["Died"].str.contains("in", na=True)])

5164

In [95]:
# number of None values
len(df[df["Died"].isna()])     # 111458

111458

In [96]:
# all the records that do not contain "in"
df[~df["Died"].str.contains("in", na=True)]["Died"]

9            27 August 1923
179                    1987
185                    1954
289            13 June 2013
291        15 December 2017
                ...
126838    16 September 2021
130149     21 December 2021
135276        12 April 1944
136653           5 May 2020
141190        10 March 2023
Name: Died, Length: 5164, dtype: object

In [97]:
# all the records that do not contain "in" and does not match the date pattern
died_date_pattern = r"(\d+ \w+ \d+)"
df[~df["Died"].str.contains("in", na=True) & ~df["Died"].str.match(died_date_pattern, na=True)]["Died"]

179                1987
185                1954
323                1967
411                2002
809                1964
              ...
108431             1971
109908             2021
115492    December 2020
116879             1986
116884             1979
Name: Died, Length: 1291, dtype: object

[2] replace the "in" and "(" with "," and the ")" with ""

In [98]:
df["Died"] = df["Died"].str.replace("in", ",", n=1)
df["Died"] = df["Died"].str.replace("(", ",")
df["Died"] = df["Died"].str.replace(")", "")
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 , Saint-Jean-de-Luz, Pyrénées-A...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-12-12,Bordeaux,Gironde,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1969-04-01,Meulan,Yvelines,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,1895-05-11,Paris VIIIe,Paris,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 , Paris VIIe, Paris ,FRA",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1878-04-17,Wandsworth,England,NaN

In [100]:
df[["Died date", "Died city", "Died region", "Died country"]] = df["Died"].str.split(",", n=3, expand=True)
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 , Saint-Jean-de-Luz, Pyrénées-A...",France,1,NaN,NaN,...,NaN,NaN,1886-12-12,Bordeaux,Gironde,NaN,2 October 1960,Saint-Jean-de-Luz,Pyrénées-Atlantiques,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,1969-04-01,Meulan,Yvelines,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN,17 July 1994,Arbonne,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,1895-05-11,Paris VIIIe,Paris,NaN,20 March 1978,Monaco,Monaco,MON
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 , Paris VIIe, Paris ,FRA",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,1878-04-17,Wandsworth,England,NaN,25 July 1930,Paris VIIe,Paris,FRA

In [ ]:
died_date_pattern = r"(\d+ \w+ \d+)"
df[~df["Died date"].str.match(died_date_pattern, na=True) & ~df["Died date"].str.match(r"(\d+)", na=True) & ~df["Died date"].str.match(r"(\w+ \d+)", na=True)]["Died date"]

693
1805
1814
1815
1846
         ..
84155
87387
97280
98395
100005
Name: Died date, Length: 246, dtype: object

In [119]:
import numpy as np
df["Died date"] = df["Died date"].replace(" ", np.nan)

In [ ]:
# replace all the blank values with None values
died_date_pattern = r"(\d+ \w+ \d+)"
blanck_values = (~df["Died date"].str.match(died_date_pattern, na=True) & ~df["Died date"].str.match(r"(\d+)", na=True) & ~df["Died date"].str.match(r"(\w+ \d+)", na=True))

df.loc[blanck_values, "Died date"] = None

In [146]:
died_date_pattern = r"(\d+ \w+ \d+)"
df[~df["Died date"].str.match(died_date_pattern, na=True) & ~df["Died date"].str.match(r"(\d+)", na=True) & ~df["Died date"].str.match(r"(\w+ \d+)", na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country]
Index: []

[0 rows x 24 columns]

In [150]:
df["Died date"] = pd.to_datetime(df["Died date"], errors="coerce")
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 , Saint-Jean-de-Luz, Pyrénées-A...",France,1,NaN,NaN,...,NaN,NaN,1886-12-12,Bordeaux,Gironde,NaN,1960-10-02,Saint-Jean-de-Luz,Pyrénées-Atlantiques,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,1969-04-01,Meulan,Yvelines,NaN,NaT,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN,1994-07-17,Arbonne,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,1895-05-11,Paris VIIIe,Paris,NaN,1978-03-20,Monaco,Monaco,MON
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 , Paris VIIe, Paris ,FRA",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,1878-04-17,Wandsworth,England,NaN,1930-07-25,Paris VIIe,Paris,FRA