In [1]:
import pandas as pd

In [2]:
original_data = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/Olympics-Dataset/refs/heads/master/athletes/bios.csv")
original_data.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
df = original_data.copy()
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

### Sex	Column
[1] make sure all the Sex column has the values of Male or Female
[2] count the null values

### Used name Column
[1] change the name of the Used name column to Name
[2] make sure all the names is not Null
[3] make sure all the names has • in it
[4] remove the • from it

### Born Column
[1] make sure that all the columns has the word "in" in them
[2] replace the "in" and "(" with "," and the ")" with ""
[3] split the column into Born date, Born city, Born region, Born country
[4] count the None values in Born date, Born city, Born region and Born country
[5] turn the Born date into datetime type

### Died Column
[1] make sure that all the columns has the word "in" in them
[2] replace the "in" and "(" with "," and the ")" with ""
[3] split the column into Died date, Died city, Died region, Died country
[4] turn the Died date into datetime type

### athlete_id Column
[1] make sure that all the values in the column are not null

### Measurements Column
[1] split the column into Height_cm and Weight_kg
[2] put the values in the Height_cm which has kg in it into Weight_kg and then remove it from Height_cm

### Sex	Column
[1] make sure all the Sex column has the values of Male or Female

In [66]:
df["Sex"].unique()

array(['Male', 'Female'], dtype=object)

[2] count the null values

In [67]:
df["Sex"].isnull().sum()

np.int64(0)

### Used name Column
[1] change the name of the Used name column to Name

In [68]:
df = df.rename(columns={"Used name":"Name"})
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[2] make sure all the names is not Null

In [69]:
df["Name"].isnull().sum()

np.int64(0)

[3] make sure all the names has • in it and remove the • from it

In [70]:
df["Name"] = df["Name"].str.replace("•", " ")
df["Name"].head()

0    Jean-François Blanchy
1           Arnaud Boetsch
2             Jean Borotra
3          Jacques Brugnon
4             Albert Canet
Name: Name, dtype: object

### Born Column

In [71]:
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[1] make sure that all the columns has the word "in" in them

In [72]:
# number of records that do not have "in" in it without Null values --> 22820
df[~df["Born"].str.contains("in", na=True)]["Born"].count()

np.int64(22820)

In [73]:
# number of records that do not have "in" in it with Null values --> 24548
len(df[~df["Born"].str.contains("in", na=False)]["Born"])

24548

In [74]:
Born_Pattern = r"(\d+ \w+ \d+)"
len(df[~df["Born"].str.contains("in", na=True) & ~df["Born"].str.match(Born_Pattern, na=True)])
len(df[~df["Born"].str.contains("in", na=True) & ~df["Born"].str.match(Born_Pattern, na=True)])

1161

[2] replace the "in" and "(" with "," and the ")" with ""

In [75]:
df["Born"] = df["Born"].str.replace("in", ",", n=1)
df["Born"] = df["Born"].str.replace("(", ",")
df["Born"] = df["Born"].str.replace(")", "")

df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

[3] split the column into Born date, Born city, Born region, Born country

In [76]:
df[["Born date", "Born city", "Born region", "Born country"]] = df["Born"].str.split(",", n=3, expand=True)
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12 December 1886,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1 April 1969,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,13 August 1898,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,11 May 1895,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,17 April 1878,Wandsworth,England,GBR

In [77]:
import numpy as np
df["Born date"] = df["Born date"].replace("", np.nan)

In [78]:
new_born_date_pattern = r"(\D+ \W+ \D+)"
df[~df["Born date"].str.match(new_born_date_pattern, na=True) & ~df["Born date"].str.match(r"(\d)", na=True)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
2209,Competed in Olympic Games,Female,"Lenora Josephine ""Leonie""•Taylor",Leonie Taylor,"March 1870 , Cincinnati, Ohio ,USA","9 March 1936 in Mount Sterling, Kentucky (USA)",United States,2219,NaN,"Cincinnati Archers, Cincinnati (USA)",NaN,NaN,NaN,NaN,NaN,NaN,March 1870,Cincinnati,Ohio,USA
2218,Competed in Olympic Games,Male,William Allen•Clark,William Clark,"March 1842 , Cincinnati, Ohio ,USA","20 October 1913 in Knoxville, Tennessee (USA)",United States,2228,NaN,"Cincinnati Archers, Cincinnati (USA)",NaN,NaN,NaN,NaN,NaN,NaN,March 1842,Cincinnati,Ohio,USA
2222,Competed in Olympic Games,Male,Edward Williston•Frentz,Edward Frentz,"May 1863 , ?, Maine ,USA","28 August 1943 in Melrose, Massachusetts (USA)",United States,2232,NaN,"Boston Archery Club, Boston (USA)",NaN,NaN,NaN,NaN,NaN,NaN,May 1863,?,Maine,USA
2744,Competed in Olympic Games,Male,Andrew I.•Drew,Andrew Drew,"February 1885 , ?, Missouri ,USA","12 June 1913 in Bath Township, Ohio (USA)",United States,2756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,February 1885,?,Missouri,USA
8032,Competed in Olympic Games,Male,"Alexander Indrajith ""Alex""•Obeysekera (Obeysek...",Alex Obeysekera,"March 1918 , Colombo, Basnahira ,SRI","28 April 2002 in Colombo, Basnahira (SRI)",Sri Lanka,8074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,March 1918,Colombo,Basnahira,SRI

In [79]:
len(df[df["Born city"].str.match(r"\w+ \d+", na=False)]) # 50
df[df["Born city"].str.match(r"\w+ \d+", na=False)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
1277,Competed in Olympic Games,Male,Manuel•Videla Castillo,Manuel Videla,",circa 1920",NaN,Chile,1284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,circa 1920,None,None
3865,Competed in Olympic Games,Male,"Babu ""Bob""•Lall",Bob Lall,",circa 1924","16 May 1953 in Kolkata (Calcutta), West Bengal...",India,3878,NaN,"?, Bengal (IND)",NaN,NaN,Bob Lal,NaN,NaN,NaN,NaN,circa 1924,None,None
4946,Competed in Olympic Games,Male,Manuel Eugenio•López,Manuel López,",circa 1929","9 April 1954 in Córdoba, Córdoba (ARG)",Argentina,4964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,circa 1929,None,None
5843,Competed in Olympic Games,Male,Chien•Kok-Ching,Chien Kok-Ching,",circa 1934",NaN,Chinese Taipei,5866,NaN,NaN,NaN,NaN,NaN,NaN,錢•國楨,Oriental,NaN,circa 1934,None,None
5846,Competed in Olympic Games,Male,Visit•Chaicharoen,Visit Chaicharoen,",circa 1933",NaN,Thailand,5869,NaN,NaN,NaN,NaN,Visit Chivacharern,NaN,วิสิตย์•ชัยเจริญ,NaN,NaN,circa 1933,None,None

In [80]:
# fill the NON values in the Born date column which has it's date in the Born city (c. |  circa)
df["Born date"] = df["Born date"].fillna(df[df["Born city"].str.match(r"(\w+)", na=False)]["Born city"].str.extract(r"(\d+)").squeeze())

In [81]:
df.loc[df["Born city"].str.contains("c.", na=False), "Born city"] = None
df.loc[df["Born city"].str.contains("circa", na=False), "Born city"] = None
df.loc[df["Born city"].str.contains("1926 or 1927", na=False), "Born city"] = None

In [82]:
len(df[df["Born city"].str.match(r"\w+", na=False)]) # 53
df[df["Born city"].str.match(r"\w+", na=False)].head()

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

In [83]:
df["Born date"] = pd.to_datetime(df["Born date"], errors="coerce")
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-12-12,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1969-04-01,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,1895-05-11,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1878-04-17,Wandsworth,England,GBR

### Born city

In [84]:
# replacing the ? with None vlaues in Born city
df["Born city"] = df["Born city"].replace("?", np.nan)

In [85]:
born_city_pattern = r"(\W+)"
df[~df["Born city"].str.match(born_city_pattern, na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

In [86]:
df[df["Born city"].str.contains(",", na=False)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

### Born region

In [87]:
df[df["Born region"].str.contains("-", na=False)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA
16,Competed in Olympic Games • Competed in Olympi...,Male,Guy•Forget,Guy Forget,"4 January 1965 , Casablanca, Casablanca-Settat...",NaN,France,17,189 cm / 79 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1965-01-04,None,Casablanca-Settat,MAR
24,Competed in Olympic Games,Male,Paul Émile•Lecaron,Paul Lecaron,"29 July 1863 , Neuilly-sur-Seine, Hauts-de-Sei...","17 September 1940 in Paris XVIe, Paris (FRA)",France,25,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1863-07-29,Neuilly-sur-Seine,Hauts-de-Seine,FRA
25,Competed in Olympic Games,Male,Henri•Leconte,Henri Leconte,"4 July 1963 , Lillers, Pas-de-Calais ,FRA",NaN,France,26,184 cm / 78 kg,LTC Nice,Le vengeur masqué,NaN,NaN,NaN,NaN,NaN,1963-07-04,Lillers,Pas-de-Calais,FRA
71,Competed in Olympic Games,Female,Clare Jacqueline•Wood,Clare Wood,"8 March 1968 , Zululand, KwaZulu-Natal ,RSA",NaN,Great Britain,72,175 cm / 65 kg,Southdown Lawn Tennis Club,NaN,NaN,NaN,NaN,NaN,NaN,1968-03-08,Zululand,KwaZulu-Natal,RSA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145325,Competed in Olympic Games,Female,Lidiya•Hunko,Lidiya Hunko,"10 August 1993 , Ivano-Frankivsk, Ivano-Franki...",NaN,Ukraine,149047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1993-08-10,Ivano-Frankivsk,Ivano-Frankivsk,UKR
145464,Competed in Olympic Games,Male,Joonas Aleksanteri•Nättinen,Joonas Nättinen,"3 January 1991 , Jämsä, Keski-Suomi ,FIN",NaN,Finland,149191,189 cm / 90 kg,"Severstal Cherepovets, Cherepovets (RUS)",NaN,NaN,NaN,NaN,NaN,NaN,1991-01-03,Jämsä,Keski-Suomi,FIN
145467,Competed in Olympic Games,Female,Elisa Maria•Nakab,Elisa Nakab,"8 May 1998 , Briançon, Hautes-Alpes ,FRA",NaN,Italy,149194,NaN,Sporting Club Livigno,NaN,NaN,NaN,NaN,NaN,NaN,1998-05-08,Briançon,Hautes-Alpes,FRA
145488,Competed in Olympic Games,Male,Shakeel•John,Shakeel John,"30 July 2001 , Mount Hope, Tunapuna-Piarco ,TTO",NaN,Trinidad and Tobago,149215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001-07-30,Mount Hope,Tunapuna-Piarco,TTO
145498,Competed in Olympic Games,Male,André•Foussard,André Foussard,"19 May 1899 , Niort, Deux-Sèvres ,FRA","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1899-05-19,Niort,Deux-Sèvres,FRA

In [88]:
born_region_pattern = r"(\d+)"
df[df["Born region"].str.match(born_region_pattern, na=False)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

In [89]:
born_region_pattern = r"(\w+)"
df[~df["Born region"].str.match(born_region_pattern, na=True)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-12-12,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1969-04-01,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,1895-05-11,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1878-04-17,Wandsworth,England,GBR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George Wright,"21 July 1890 , Toronto, Ontario ,CAN","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,1890-07-21,Toronto,Ontario,CAN
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina Luchnikova,"30 January 2002 , Serov, Sverdlovsk ,RUS",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,NaN,NaN,2002-01-30,Serov,Sverdlovsk,RUS
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya Smirnova,"8 May 1998 , Kotlas, Arkhangelsk ,RUS",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,Юлия•Смирнова,NaN,1998-05-08,Kotlas,Arkhangelsk,RUS
145498,Competed in Olympic Games,Male,André•Foussard,André Foussard,"19 May 1899 , Niort, Deux-Sèvres ,FRA","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1899-05-19,Niort,Deux-Sèvres,FRA
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill Phillips,"15 July 1913 , Dulwich Hill, New South Wales ,AUS","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1913-07-15,None,New South Wales,AUS

### Born country

In [90]:
born_city_pattern = r"(\w+)"
df[~df["Born country"].str.match(born_city_pattern, na=True)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
49,Competed in Olympic Games,Female,Gillian Carol•Gowers,Gillian Gowers,"9 April 1964 , Horfield, Clifton, England ,GBR",NaN,Great Britain,50,157 cm / 55 kg,Gosling,NaN,NaN,NaN,NaN,NaN,NaN,1964-04-09,Horfield,Clifton,"England ,GBR"
80,Competed in Olympic Games,Male,George Aristides•Caridia (Karidias-),George Caridia,"20 February 1869 , Kolkata ,Calcutta, West Ben...","21 April 1937 in Marylebone, England (GBR)",Great Britain,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1869-02-20,Kolkata,Calcutta,"West Bengal ,IND"
101,Competed in Olympic Games,Male,Algernon Robert Fitzhardinge•Kingscote,Algernon Kingscote,"3 February 1888 , Bengaluru ,Bangalore, Karnat...","21 December 1964 in Woking, England (GBR)",Great Britain,102,NaN,NaN,Algy,NaN,NaN,NaN,NaN,NaN,1888-02-03,Bengaluru,Bangalore,"Karnataka ,IND"
103,Competed in Olympic Games,Male,Arthur Holden•Lowe,Arthur Lowe,"29 January 1886 , Edgbaston, Birmingham, Engla...","22 October 1958 in London, England (GBR)",Great Britain,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-01-29,Edgbaston,Birmingham,"England ,GBR"
104,Competed in Olympic Games,Male,Francis Gordon•Lowe,Gordon Lowe,"21 June 1884 , Edgbaston, Birmingham, England ...","17 May 1972 in London, England (GBR)",Great Britain,105,NaN,NaN,NaN,2nd Baronet of Lowe,NaN,NaN,NaN,NaN,1884-06-21,Edgbaston,Birmingham,"England ,GBR"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145450,Competed in Olympic Games,Female,Anna Stanislavovna•Shcherbakova,Anna Shcherbakova,"28 March 2004 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149174,NaN,NaN,NaN,NaN,NaN,NaN,Анна Станиславовна•Щербакова,NaN,2004-03-28,Moskva,Moscow,"Moskva ,RUS"
145465,Competed in Olympic Games,Male,Stanislav Sergeyevich•Galiyev,Stanislav Galiyev,"17 January 1992 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149192,188 cm / 82 kg,"Dynamo Moskva, Moskva (RUS)",NaN,NaN,NaN,NaN,Станислав Сергеевич•Галиев,NaN,1992-01-17,Moskva,Moscow,"Moskva ,RUS"
145487,Competed in Olympic Games,Female,Yekaterina Aleksandrovna•Kosova,Yekaterina Kosova,"25 April 1996 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149214,NaN,NaN,NaN,NaN,NaN,NaN,Екатерина Александровна•Косова,NaN,1996-04-25,Moskva,Moscow,"Moskva ,RUS"
145492,Competed in Olympic Games,Male,Carlos•García-Ordóñez Montalvo,Carlos García-Ordóñez,"24 April 1927 , La Habana ,Havana, Ciudad de L...","24 November 2019 in Miami, Florida (USA)",Cuba,149219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1927-04-24,La Habana,Havana,"Ciudad de La Habana ,CUB"
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya Merkusheva,"20 September 1999 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Валерия Сергеевна•Меркушева,NaN,1999-09-20,Moskva,Moscow,"Moskva ,RUS"

In [91]:
df["Born country"] = df[df["Born country"].str.contains(",", na=False)]["Born country"].str.extract(r",(\w+)").squeeze()

In [92]:
born_city_pattern = r"(\w+)"
df[~df["Born country"].str.match(born_city_pattern, na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country]
Index: []

### Died Column
[1] make sure that all the columns has the word "in" in them

In [93]:
# number of records that contain "in" without the None values
len(df[df["Died"].str.contains("in", na=False)])    # 28878

28878

In [94]:
# number of records that do not contain "in"
len(df[~df["Died"].str.contains("in", na=True)])

5164

In [95]:
# number of None values
len(df[df["Died"].isna()])     # 111458

111458

In [96]:
# all the records that do not contain "in"
df[~df["Died"].str.contains("in", na=True)]["Died"]

9            27 August 1923
179                    1987
185                    1954
289            13 June 2013
291        15 December 2017
                ...
126838    16 September 2021
130149     21 December 2021
135276        12 April 1944
136653           5 May 2020
141190        10 March 2023
Name: Died, Length: 5164, dtype: object

In [97]:
# all the records that do not contain "in" and does not match the date pattern
died_date_pattern = r"(\d+ \w+ \d+)"
df[~df["Died"].str.contains("in", na=True) & ~df["Died"].str.match(died_date_pattern, na=True)]["Died"]

179                1987
185                1954
323                1967
411                2002
809                1964
              ...
108431             1971
109908             2021
115492    December 2020
116879             1986
116884             1979
Name: Died, Length: 1291, dtype: object

[2] replace the "in" and "(" with "," and the ")" with ""

In [98]:
df["Died"] = df["Died"].str.replace("in", ",", n=1)
df["Died"] = df["Died"].str.replace("(", ",")
df["Died"] = df["Died"].str.replace(")", "")
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,Born date,Born city,Born region,Born country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 , Saint-Jean-de-Luz, Pyrénées-A...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1886-12-12,Bordeaux,Gironde,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1969-04-01,Meulan,Yvelines,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,1895-05-11,Paris VIIIe,Paris,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 , Paris VIIe, Paris ,FRA",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,1878-04-17,Wandsworth,England,NaN

In [100]:
df[["Died date", "Died city", "Died region", "Died country"]] = df["Died"].str.split(",", n=3, expand=True)
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 , Saint-Jean-de-Luz, Pyrénées-A...",France,1,NaN,NaN,...,NaN,NaN,1886-12-12,Bordeaux,Gironde,NaN,2 October 1960,Saint-Jean-de-Luz,Pyrénées-Atlantiques,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,1969-04-01,Meulan,Yvelines,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN,17 July 1994,Arbonne,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,1895-05-11,Paris VIIIe,Paris,NaN,20 March 1978,Monaco,Monaco,MON
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 , Paris VIIe, Paris ,FRA",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,1878-04-17,Wandsworth,England,NaN,25 July 1930,Paris VIIe,Paris,FRA

In [ ]:
died_date_pattern = r"(\d+ \w+ \d+)"
df[~df["Died date"].str.match(died_date_pattern, na=True) & ~df["Died date"].str.match(r"(\d+)", na=True) & ~df["Died date"].str.match(r"(\w+ \d+)", na=True)]["Died date"]

693
1805
1814
1815
1846
         ..
84155
87387
97280
98395
100005
Name: Died date, Length: 246, dtype: object

In [119]:
import numpy as np
df["Died date"] = df["Died date"].replace(" ", np.nan)

In [ ]:
# replace all the blank values with None values
died_date_pattern = r"(\d+ \w+ \d+)"
blanck_values = (~df["Died date"].str.match(died_date_pattern, na=True) & ~df["Died date"].str.match(r"(\d+)", na=True) & ~df["Died date"].str.match(r"(\w+ \d+)", na=True))

df.loc[blanck_values, "Died date"] = None

In [146]:
died_date_pattern = r"(\d+ \w+ \d+)"
df[~df["Died date"].str.match(died_date_pattern, na=True) & ~df["Died date"].str.match(r"(\d+)", na=True) & ~df["Died date"].str.match(r"(\w+ \d+)", na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country]
Index: []

[0 rows x 24 columns]

In [150]:
df["Died date"] = pd.to_datetime(df["Died date"], errors="coerce")
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 , Saint-Jean-de-Luz, Pyrénées-A...",France,1,NaN,NaN,...,NaN,NaN,1886-12-12,Bordeaux,Gironde,NaN,1960-10-02,Saint-Jean-de-Luz,Pyrénées-Atlantiques,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,1969-04-01,Meulan,Yvelines,NaN,NaT,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN,1994-07-17,Arbonne,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,1895-05-11,Paris VIIIe,Paris,NaN,1978-03-20,Monaco,Monaco,MON
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 , Paris VIIe, Paris ,FRA",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,1878-04-17,Wandsworth,England,NaN,1930-07-25,Paris VIIe,Paris,FRA

In [154]:
died_city_pattern = r"(\w+)"
df[df["Died city"].str.match(died_city_pattern, na=False)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
1805,Competed in Olympic Games,Male,Gharib Ibrahim•Afifi,Gharib Afifi,", Al-Qahira ,Cairo, Al-Qahira ,EGY",",In the 1990s",Egypt,1812,NaN,"El-Olympi, Al-Iskanderiya (EGY)",...,غريب ابراهيم•عفيفي,NaN,NaT,Al-Qahira,Cairo,EGY,NaT,In the 1990s,None,None
1814,Competed in Olympic Games,Male,Badawi•El-Bedewi,Badawi El-Bedewi,"14 May 1942 , El-Mahalla El-Kubra, Al-Gharbiya...",",Prior to 2016",Egypt,1822,NaN,NaN,...,بدوي•البدوي,NaN,1942-05-14,El-Mahalla El-Kubra,Al-Gharbiyah,NaN,NaT,Prior to 2016,None,None
1815,Competed in Olympic Games,Male,Muhammad Moussa•El-Gelidi,Moussa El-Gelidi,"14 April 1932 , Al-Iskanderiya ,Alexandria, Al...",",before 2013",United Arab Republic,1823,NaN,NaN,...,محمد موسى•الجليدي,NaN,1932-04-14,Al-Iskanderiya,Alexandria,EGY,NaT,before 2013,None,None
1846,Competed in Olympic Games,Male,Hussein•Saddik,Hussein Saddik,"5 April 1939 , Al-Iskanderiya ,Alexandria, Al-...",",Prior to 2016",Egypt,1855,NaN,"El-Olympi, Al-Iskanderiya (EGY)",...,حسين•صديق,NaN,1939-04-05,Al-Iskanderiya,Alexandria,EGY,NaT,Prior to 2016,None,None
2982,Competed in Olympic Games,Male,Guitry•Bananier,Guitry Bananier,11 June 1951,",early 1980s",France,2994,167 cm / 60 kg,NaN,...,NaN,NaN,NaT,None,None,NaN,NaT,early 1980s,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83264,Competed in Olympic Games,Male,Reza•Bazargan,Reza Bazargan,"1931 , Tehran, Tehran ,IRI",",Between 2006 and 2010",Islamic Republic of Iran,83922,NaN,NaN,...,رضا•بازرگان,NaN,NaT,Tehran,Tehran,NaN,NaT,Between 2006 and 2010,None,None
84155,Competed in Olympic Games,Male,Ion•Coliban,Ion Coliban,"6 June 1925 , Brașov, Brașov ,ROU",",Deceased, details unknown",Romania,84824,NaN,"Steaua București, București (ROU)",...,NaN,NaN,1925-06-06,Brașov,Brașov,NaN,NaT,Deceased,details unknown,None
87387,Competed in Olympic Games,Male,Fritz Paul•Kocher,Fritz Kocher,"6 April 1928 , Bern, Bern ,SUI",",prior to 2018",Switzerland,88084,NaN,"SC Altstetten, Zürich (SUI) / SC Wald, Wald (SUI)",...,NaN,NaN,1928-04-06,Bern,Bern,NaN,NaT,prior to 2018,None,None
97280,Competed in Olympic Games,Male,Tamás•Székely,Tamás Székely,29 April 1923,",Prior to 2007",Hungary,98066,NaN,"MAFC, Budapest (HUN)",...,NaN,NaN,NaT,None,None,NaN,NaT,Prior to 2007,None,None
100005,Competed in Olympic Games,Male,Durga Charan•Das,Durga Das,1920,",Deceased, details unknown",India,100831,NaN,"College Square Swimming Club, Kolkata (IND)",...,NaN,NaN,NaT,None,None,NaN,NaT,Deceased,details unknown,None

In [165]:
df[df["Died city"].str.contains("before|Prior|prior|Deceased|Between", na=False, regex=True)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
584,Competed in Olympic Games,Male,Charles John Perry•Keene,Perry Keene,"11 April 1846 , Minety, England ,GBR","29 November 1926 , Dean Prior, England ,GBR",Great Britain,586,NaN,"Devon and Cornwall AS, (GBR)",...,NaN,NaN,1846-04-11,Minety,England,NaN,1926-11-29,Dean Prior,England,GBR
1814,Competed in Olympic Games,Male,Badawi•El-Bedewi,Badawi El-Bedewi,"14 May 1942 , El-Mahalla El-Kubra, Al-Gharbiya...",",Prior to 2016",Egypt,1822,NaN,NaN,...,بدوي•البدوي,NaN,1942-05-14,El-Mahalla El-Kubra,Al-Gharbiyah,NaN,NaT,Prior to 2016,None,None
1815,Competed in Olympic Games,Male,Muhammad Moussa•El-Gelidi,Moussa El-Gelidi,"14 April 1932 , Al-Iskanderiya ,Alexandria, Al...",",before 2013",United Arab Republic,1823,NaN,NaN,...,محمد موسى•الجليدي,NaN,1932-04-14,Al-Iskanderiya,Alexandria,EGY,NaT,before 2013,None,None
1846,Competed in Olympic Games,Male,Hussein•Saddik,Hussein Saddik,"5 April 1939 , Al-Iskanderiya ,Alexandria, Al-...",",Prior to 2016",Egypt,1855,NaN,"El-Olympi, Al-Iskanderiya (EGY)",...,حسين•صديق,NaN,1939-04-05,Al-Iskanderiya,Alexandria,EGY,NaT,Prior to 2016,None,None
3903,Competed in Olympic Games,Male,George•Issabeg,George Issabeg,9 November 1930,",Deceased, details unknown",Islamic Republic of Iran,3916,NaN,NaN,...,ژرژ•عیسی‌بک,NaN,NaT,None,None,NaN,NaT,Deceased,details unknown,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84155,Competed in Olympic Games,Male,Ion•Coliban,Ion Coliban,"6 June 1925 , Brașov, Brașov ,ROU",",Deceased, details unknown",Romania,84824,NaN,"Steaua București, București (ROU)",...,NaN,NaN,1925-06-06,Brașov,Brașov,NaN,NaT,Deceased,details unknown,None
87387,Competed in Olympic Games,Male,Fritz Paul•Kocher,Fritz Kocher,"6 April 1928 , Bern, Bern ,SUI",",prior to 2018",Switzerland,88084,NaN,"SC Altstetten, Zürich (SUI) / SC Wald, Wald (SUI)",...,NaN,NaN,1928-04-06,Bern,Bern,NaN,NaT,prior to 2018,None,None
95880,Competed in Olympic Games,Male,Merritt Grabiel•Putman,Merritt Putman,"22 February 1900 , Ottawa, Ontario ,CAN","8 January 1989 , Arnprior, Ontario ,CAN",Canada,96654,NaN,"Toronto Ski Club, Toronto (CAN) / Ski Club of ...",...,NaN,NaN,1900-02-22,Ottawa,Ontario,NaN,1989-01-08,Arnprior,Ontario,CAN
97280,Competed in Olympic Games,Male,Tamás•Székely,Tamás Székely,29 April 1923,",Prior to 2007",Hungary,98066,NaN,"MAFC, Budapest (HUN)",...,NaN,NaN,NaT,None,None,NaN,NaT,Prior to 2007,None,None
100005,Competed in Olympic Games,Male,Durga Charan•Das,Durga Das,1920,",Deceased, details unknown",India,100831,NaN,"College Square Swimming Club, Kolkata (IND)",...,NaN,NaN,NaT,None,None,NaN,NaT,Deceased,details unknown,None

In [196]:
dirty_died_city = df["Died city"].str.contains("Before|before|Prior|prior|Deceased|Between|Died|died|In the|early|late|between|circa|Around|Declared|deceased|c.|or|Shortly|At the age of|\?", na=False, regex=True)
df.loc[dirty_died_city, "Died city"] = None

In [197]:
df[df["Died city"].str.contains("Before|before|Prior|prior|Deceased|Between|Died|died|In the|early|late|between|circa|Around|Declared|deceased|c.|or|Shortly|At the age of|\?", na=False, regex=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country]
Index: []

[0 rows x 24 columns]

In [198]:
died_city_pattern = r"(\w+)"
df[df["Died city"].str.match(died_city_pattern, na=False)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country]
Index: []

[0 rows x 24 columns]

In [200]:
died_region_pattern = r"(\w+)"
df[df["Died region"].str.match(died_region_pattern, na=False)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
180,Competed in Olympic Games,Male,"Chios ""Konstantinos""•Paspatis",Konstantinos Paspatis,"5 June 1878 , West Derby, Liverpool, England ,GBR","1 July 1903 , Athina ,Athens, Attiki ,GRE",Greece,181,NaN,"Athens Lawn Tennis Club, Athina (GRE)",...,"Χίος ""Κωνσταντίνος""•Πασπατις",NaN,1878-06-05,West Derby,Liverpool,GBR,1903-07-01,Athina,Athens,"Attiki ,GRE"
649,Competed in Olympic Games,Male,Rolf•Kinzl,Rolf Kinzl,"19 October 1878 , Praha ,Prague, Hlavní město ...","14 November 1938 , Wien ,Vienna, Wien ,AUT",Austria,652,NaN,NaN,...,NaN,NaN,1878-10-19,Praha,Prague,CZE,1938-11-14,Wien,Vienna,"Wien ,AUT"
678,Competed in Olympic Games,Male,Albert T. E.•Lammens,Albert Lammens,"17 June 1890 , Bruxelles ,Brussels, Région de ...","7 October 1933 , Gent ,Ghent, Oost-Vlaanderen ...",Belgium,681,NaN,NaN,...,NaN,NaN,1890-06-17,Bruxelles,Brussels,BEL,1933-10-07,Gent,Ghent,"Oost-Vlaanderen ,BEL"
682,Competed in Olympic Games,Male,Jean Marie Octave Constant•Washer,Jean Washer,"22 August 1894 , Berchem, Antwerpen ,BEL","23 March 1972 , Genève ,Geneva, Genève ,SUI",Belgium,685,NaN,"Royal Léopold Club, Bruxelles (BEL)",...,NaN,NaN,1894-08-22,None,Antwerpen,NaN,1972-03-23,Genève,Geneva,"Genève ,SUI"
691,Competed in Olympic Games,Female,"Hedwig•Rosenbaum (Austerlitz-, -Raabe)",Hedwig Rosenbaum,"3 July 1864 , Praha ,Prague, Hlavní město Prah...","31 July 1939 , Praha ,Prague, Hlavní město Pra...",Bohemia,694,NaN,"LTC Praha, Praha (CZE)",...,NaN,NaN,1864-07-03,Praha,Prague,CZE,1939-07-31,Praha,Prague,"Hlavní město Praha ,CZE"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130077,Competed in Olympic Games,Male,Aliaksei Uladzimiravich•Mzhachyk,Aliaksei Mzhachyk,"30 June 1996 , Pinsk, Brest ,BLR","1 August 2021 , ? ,GER",Belarus,132731,190 cm / 135 kg,NaN,...,Аляксей Уладзіміравіч•Мжачўк,NaN,1996-06-30,Pinsk,Brest,NaN,2021-08-01,None,GER,None
132713,Competed in Olympic Games,Male,Abdalelah•Haroun Hassan,Abdalelah Haroun,"1 January 1997 , Al-Soki, Sennar ,SUD","26 June 2021 , Ad-Dawhah ,Doha, Ad-Dawhah ,QAT",Qatar,135607,185 cm / 80 kg,NaN,...,عبد الإله•هارون,NaN,1997-01-01,Al-Soki,Sennar,NaN,2021-06-26,Ad-Dawhah,Doha,"Ad-Dawhah ,QAT"
133701,Competed in Olympic Games,Female,Ekaterina•Alexandrovskaya,Ekaterina Alexandrovskaya,"1 January 2000 , Moskva ,Moscow, Moskva ,RUS","18 July 2020 , Moskva ,Moscow, Moskva ,RUS",Australia,136685,154 cm / 43 kg,Sydney Figure Skating Club (AUS),...,NaN,NaN,2000-01-01,Moskva,Moscow,RUS,2020-07-18,Moskva,Moscow,"Moskva ,RUS"
135281,Competed in Olympic Games,Male,Louis•Renaud,Louis Renaud,"6 December 1888 , Buenos Aires, Ciudad Autónom...","September 1939 , ? ,EGY",France,138444,NaN,Salle Lambert et Jeanvoix,...,NaN,NaN,1888-12-06,Buenos Aires,Ciudad Autónoma de Buenos Aires,NaN,NaT,None,EGY,None
135284,Competed in Olympic Games,Male,Albert Edward•Hawkins,Albert Hawkins,"21 May 1886 , Abertillery, Wales ,GBR","1969 , Glamorgan ,GBR",Great Britain,138447,NaN,"Powell's Tillery Gymnastics Club, Abertillery ...",...,NaN,NaN,1886-05-21,Abertillery,Wales,NaN,NaT,None,GBR,None

In [201]:
# take values from the "Died country" column that are exactly 3 uppercase letters and put them into the "Died region" column.
mask = df["Died region"].str.match(r"^[A-Z]{3}$", na=False)

df.loc[mask, "Died country"] = df.loc[mask, "Died region"]

In [ ]:
# removing the values from Died region column
df.loc[mask, "Died region"] = None

In [205]:
died_region_pattern = r"(\w+)"
df[df["Died region"].str.match(died_region_pattern, na=False)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
180,Competed in Olympic Games,Male,"Chios ""Konstantinos""•Paspatis",Konstantinos Paspatis,"5 June 1878 , West Derby, Liverpool, England ,GBR","1 July 1903 , Athina ,Athens, Attiki ,GRE",Greece,181,NaN,"Athens Lawn Tennis Club, Athina (GRE)",...,"Χίος ""Κωνσταντίνος""•Πασπατις",NaN,1878-06-05,West Derby,Liverpool,GBR,1903-07-01,Athina,Athens,"Attiki ,GRE"
649,Competed in Olympic Games,Male,Rolf•Kinzl,Rolf Kinzl,"19 October 1878 , Praha ,Prague, Hlavní město ...","14 November 1938 , Wien ,Vienna, Wien ,AUT",Austria,652,NaN,NaN,...,NaN,NaN,1878-10-19,Praha,Prague,CZE,1938-11-14,Wien,Vienna,"Wien ,AUT"
678,Competed in Olympic Games,Male,Albert T. E.•Lammens,Albert Lammens,"17 June 1890 , Bruxelles ,Brussels, Région de ...","7 October 1933 , Gent ,Ghent, Oost-Vlaanderen ...",Belgium,681,NaN,NaN,...,NaN,NaN,1890-06-17,Bruxelles,Brussels,BEL,1933-10-07,Gent,Ghent,"Oost-Vlaanderen ,BEL"
682,Competed in Olympic Games,Male,Jean Marie Octave Constant•Washer,Jean Washer,"22 August 1894 , Berchem, Antwerpen ,BEL","23 March 1972 , Genève ,Geneva, Genève ,SUI",Belgium,685,NaN,"Royal Léopold Club, Bruxelles (BEL)",...,NaN,NaN,1894-08-22,None,Antwerpen,NaN,1972-03-23,Genève,Geneva,"Genève ,SUI"
691,Competed in Olympic Games,Female,"Hedwig•Rosenbaum (Austerlitz-, -Raabe)",Hedwig Rosenbaum,"3 July 1864 , Praha ,Prague, Hlavní město Prah...","31 July 1939 , Praha ,Prague, Hlavní město Pra...",Bohemia,694,NaN,"LTC Praha, Praha (CZE)",...,NaN,NaN,1864-07-03,Praha,Prague,CZE,1939-07-31,Praha,Prague,"Hlavní město Praha ,CZE"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120307,Competed in Olympic Games,Female,Bobana•Veličković,Bobana Veličković,"25 January 1990 , Kosjerić, Zlatibor ,SRB","21 June 2020 , Beograd ,Belgrade, Beograd ,SRB",Serbia,122191,170 cm / 59 kg,NaN,...,Бобана•Величковић,NaN,1990-01-25,Kosjerić,Zlatibor,NaN,2020-06-21,Beograd,Belgrade,"Beograd ,SRB"
122347,Competed in Olympic Games,Male,Abdelrahman Yahia Abdulsalam Muhammad•El-Trabily,Abdelrahman El-Trabily,"7 September 1989 , Bur Said ,Port Said, Bur Sa...","16 August 2013 , Bur Said ,Port Said, Bur Said...",Egypt,124422,190 cm / 120 kg,NaN,...,عبد الرحمن يحيي عبد السلام محمد•الطرابيلي,NaN,1989-09-07,Bur Said,Port Said,EGY,2013-08-16,Bur Said,Port Said,"Bur Said ,EGY"
125504,Competed in Olympic Games,Female,Sophie•Kratzer,Sophie Kratzer,"20 April 1989 , Landshut, Bayern ,GER","13 January 2020 , München ,Munich, Bayern ,GER",Germany,127849,171 cm / 71 kg,"ESC Planegg-Würmtal, Planegg (GER)",...,NaN,NaN,1989-04-20,Landshut,Bayern,NaN,2020-01-13,None,Munich,"Bayern ,GER"
132713,Competed in Olympic Games,Male,Abdalelah•Haroun Hassan,Abdalelah Haroun,"1 January 1997 , Al-Soki, Sennar ,SUD","26 June 2021 , Ad-Dawhah ,Doha, Ad-Dawhah ,QAT",Qatar,135607,185 cm / 80 kg,NaN,...,عبد الإله•هارون,NaN,1997-01-01,Al-Soki,Sennar,NaN,2021-06-26,Ad-Dawhah,Doha,"Ad-Dawhah ,QAT"
133701,Competed in Olympic Games,Female,Ekaterina•Alexandrovskaya,Ekaterina Alexandrovskaya,"1 January 2000 , Moskva ,Moscow, Moskva ,RUS","18 July 2020 , Moskva ,Moscow, Moskva ,RUS",Australia,136685,154 cm / 43 kg,Sydney Figure Skating Club (AUS),...,NaN,NaN,2000-01-01,Moskva,Moscow,RUS,2020-07-18,Moskva,Moscow,"Moskva ,RUS"

In [214]:
df[df["Died country"].str.contains(",", na=False)]["Died country"].str.extract(r",(\w+)").squeeze()

86        GBR
180       GRE
552       GBR
649       AUT
678       BEL
         ...
125504    GER
126487    POR
132713    QAT
133701    RUS
135273    FRA
Name: 0, Length: 3659, dtype: object

In [ ]:
# removing any values in the Died country column except the 3 Upper case from Died country column
df["Died country"] = df[df["Died country"].str.contains(",", na=False)]["Died country"].str.extract(r",(\w+)").squeeze()

In [217]:
df[df["Died country"].str.contains(",", na=False)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country]
Index: []

[0 rows x 24 columns]

In [219]:
df[~df["Died country"].str.match(r"^[A-Z]{3}$", na=True)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
8399,Competed in Olympic Games,Male,Mohamed•Muruli,Mohamed Muruli,"13 July 1947 , Kichwamba, Busoga, Eastern ,UGA","1995 , Fort Portal, Western ,UGA ,Prior to 2014",Uganda,8445,170 cm / 64 kg,NaN,...,NaN,NaN,1947-07-13,None,Busoga,UGA,NaT,None,Western,Prior
14911,Competed in Olympic Games,Male,Rudolf Horst•Karsch,Rudolf Karsch,"26 December 1913 , Leipzig, Sachsen ,GER","10 December 1950 , Leipzig, Sachsen ,GER ,Died...",Germany,15012,NaN,"RC Wettina 06, Leipzig (GER)",...,NaN,NaN,1913-12-26,Leipzig,Sachsen,NaN,1950-12-10,Leipzig,Sachsen,Died
25231,Competed in Olympic Games,Male,Julius•Hirsch,Julius Hirsch,"7 April 1892 , Achern, Baden-Württemberg ,GER","8 May 1945 , Oświęcim, Małopolskie ,POL ,decla...",Germany,25421,NaN,"Karlsruher FV, Karlsruhe (GER)",...,NaN,NaN,1892-04-07,None,Baden-Württemberg,NaN,1945-05-08,None,Małopolskie,declared
26782,Competed in Olympic Games,Male,Leon•Sperling,Leon Sperling,"17 August 1901 , Kraków ,Cracow, Małopolskie ,POL","December 1941 , Lviv, Lviv ,UKR ,Between 15 an...",Poland,26977,165 cm / 63 kg,"Cracovia, Kraków (POL)",...,NaN,NaN,1901-08-17,Kraków,Cracow,POL,NaT,Lviv,Lviv,Between
30785,Competed in Olympic Games,Male,August•Güttinger,August Güttinger,10 July 1892,"November 1970 , Winterthur, Zürich ,SUI ,Died ...",Switzerland,31021,NaN,Veltheim,...,NaN,NaN,NaT,None,None,NaN,NaT,Winterthur,Zürich,Died
31848,Competed in Olympic Games,Male,Artur•Knautz,Artur Knautz,"20 March 1911 , Daaden, Daaden-Herdorf, Rheinl...","1 August 1943 , Belgorod, Belgorod ,RUS ,missi...",Germany,32087,NaN,"MSH Minden, Minden (GER)",...,NaN,NaN,1911-03-20,Daaden,Daaden-Herdorf,GER,1943-08-01,None,Belgorod,missing
34444,Competed in Olympic Games,Male,Joaquín•Villalba Sánchez de Ocaña,Joaquín Villalba,"29 September 1928 , Pamplona, Navarra ,ESP","26 November 2007 , Madrid, Madrid ,ESP ,Prior ...",Spain,34711,175 cm / 73 kg,NaN,...,NaN,NaN,1928-09-29,Pamplona,Navarra,NaN,2007-11-26,Madrid,Madrid,Prior
35485,Competed in Olympic Games,Male,Edmond•Vanwaes,Edmond Vanwaes,"8 March 1892 , Ledeberg, Oost-Vlaanderen ,BEL","31 May 1944 , Natzwiller, Bas-Rhin ,FRA ,Died ...",Belgium,35763,NaN,"KRSG, Gent (BEL)",...,NaN,NaN,1892-03-08,Ledeberg,Oost-Vlaanderen,NaN,1944-05-31,Natzwiller,Bas-Rhin,Died
37701,Competed in Olympic Games,Male,Joachim Richard Julius Gustav•Spremberg,Joachim Spremberg,"3 November 1908 , Berlin, Berlin ,GER","16 July 1975 , West-Berlin, Berlin ,GER ,Decea...",Germany,37999,NaN,"BRC, Berlin (GER)",...,NaN,NaN,1908-11-03,Berlin,Berlin,NaN,1975-07-16,West-Berlin,Berlin,Deceased
55462,Competed in Olympic Games,Male,Hermann Willi•Reinfrank,Willi Reinfrank,"30 May 1903 , Mannheim, Baden-Württemberg ,GER","1 January 1943 , Volgograd, Volgograd ,RUS ,mi...",Germany,55858,NaN,VfK 86 Mannheim,...,NaN,NaN,1903-05-30,Mannheim,Baden-Württemberg,NaN,1943-01-01,Volgograd,Volgograd,missing
66152,Competed in Olympic Games,Male,Francisco J.•Gutiérrez Hernández,Francisco Gutiérrez,"3 December 1941 , Cartagena de Indias, Bolívar...","December 2017 , Cartagena de Indias, Bolívar ,...",Colombia,66656,175 cm / 70 kg,NaN,...,NaN,NaN,1941-12-03,Cartagena de Indias,Bolívar,NaN,NaT,Cartagena de Indias,Bolívar,Died
72547,Competed in Olympic Games,Male,Teodors•Sukatnieks,Teodors Sukatnieks,"19 May 1894 , Ventspils, Ventspils ,LAT",", Yekaterinburg, Sverdlovsk ,RUS ,Between 1941...",Latvia,73099,NaN,Ventspils Spars,...,NaN,NaN,1894-05-19,Ventspils,Ventspils,NaN,NaT,Yekaterinburg,Sverdlovsk,Between
73435,Competed in Olympic Games,Male,Muslim Aremu•Arogundade,Muslim Arogundade,"24 June 1926 , Ibadan, Oyo ,NGR",", Lagos, Lagos ,NGR ,Deceased, details unknown",Nigeria,74001,NaN,"Lagos United African Company Club, Lagos (NGR)",...,NaN,NaN,1926-06-24,Ibadan,Oyo,NaN,NaT,Lagos,Lagos,Deceased
83783,Competed in Olympic Games,Male,Alexandru•Budișteanu,Alexandru Budișteanu,10 October 1907,"1951 , Brașov, Brașov ,ROU ,Died in Jan/Feb 1951",Romania,84449,NaN,NaN,...,NaN,NaN,NaT,None,None,NaN,NaT,Brașov,Brașov,Died
97035,Competed in Olympic Games • Referee,Male,Alfred Paul•Steinke,Alfred Steinke,"6 June 1881 , Berlin, Berlin ,GER","1947 , Neubrandenburg, Mecklenburg-Vorpommern ...",Germany,97815,NaN,"Berliner Schlittschuhclub, Berlin (GER)",...,NaN,NaN,1881-06-06,Berlin,Berlin,NaN,NaT,Neubrandenburg,Mecklenburg-Vorpommern,Died

In [ ]:
# removing any invalid values in the column
dirty_died_country = df["Died country"].str.contains("Died|Deceased|Between|missing|Prior|declared|", na=False, regex=True)
df.loc[dirty_died_country, "Died country"] = None

In [221]:
df[~df["Died country"].str.match(r"^[A-Z]{3}$", na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country]
Index: []

[0 rows x 24 columns]

### Measurements Column
[1] split the column into Height_cm and Weight_kg

In [224]:
len(df[df["Measurements"].str.contains("/", na=False)])

103028

In [223]:
df[df["Measurements"].str.contains("/", na=False)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,1969-04-01,Meulan,Yvelines,NaN,NaT,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN,1994-07-17,Arbonne,Pyrénées-Atlantiques,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,1895-05-11,Paris VIIIe,Paris,NaN,1978-03-20,None,Monaco,NaN
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas Chatelain,"13 January 1970 , Amiens, Somme ,FRA",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",...,NaN,NaN,1970-01-13,Amiens,Somme,NaN,NaT,NaN,NaN,NaN
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick Chila,"27 November 1969 , Ris-Orangis, Essonne ,FRA",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",...,NaN,NaN,1969-11-27,Ris-Orangis,Essonne,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145473,Competed in Olympic Games,Male,Toms•Andersons,Toms Andersons,"25 November 1993 , Rīga, Rīga ,LAT",NaN,Latvia,149200,185 cm / 86 kg,"HC La Chaux-de-Fonds, La Chaux-de-Fonds (SUI)",...,NaN,NaN,1993-11-25,Rīga,Rīga,NaN,NaT,NaN,NaN,NaN
145474,Competed in Olympic Games,Female,Nadine•Hofstetter,Nadine Hofstetter,"21 October 1994 , Romoos, Luzern ,SUI",NaN,Switzerland,149201,164 cm / 68 kg,"SC Reinach, Reinach (SUI)",...,NaN,NaN,1994-10-21,Romoos,Luzern,NaN,NaT,NaN,NaN,NaN
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina Luchnikova,"30 January 2002 , Serov, Sverdlovsk ,RUS",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",...,NaN,NaN,2002-01-30,Serov,Sverdlovsk,NaN,NaT,NaN,NaN,NaN
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya Merkusheva,"20 September 1999 , Moskva ,Moscow, Moskva ,RUS",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",...,Валерия Сергеевна•Меркушева,NaN,1999-09-20,Moskva,Moscow,RUS,NaT,NaN,NaN,NaN
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya Smirnova,"8 May 1998 , Kotlas, Arkhangelsk ,RUS",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",...,Юлия•Смирнова,NaN,1998-05-08,Kotlas,Arkhangelsk,NaN,NaT,NaN,NaN,NaN

In [227]:
len(df[~df["Measurements"].str.contains("/", na=True)])

4805

In [226]:
df[~df["Measurements"].str.contains("/", na=True)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie Doherty,"8 October 1875 , Wimbledon, England ,GBR","21 August 1919 , Broadstairs, England ,GBR",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",...,NaN,NaN,1875-10-08,Wimbledon,England,NaN,1919-08-21,Broadstairs,England,NaN
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold Mahony,"13 February 1867 , Edinburgh, Scotland ,GBR","27 June 1905 , between Glencar and Killorgin, ...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",...,NaN,NaN,1867-02-13,Edinburgh,Scotland,NaN,1905-06-27,None,Kerry,NaN
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,...,NaN,NaN,NaT,None,None,NaN,NaT,NaN,NaN,NaN
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy Susanti,"11 February 1971 , Tasikmalaya, Jawa Barat ,INA",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",...,NaN,NaN,1971-02-11,Tasikmalaya,Jawa Barat,NaN,NaT,NaN,NaN,NaN
243,Competed in Olympic Games,Female,Lili•Tampi,Lili Tampi,"19 May 1970 , Tasikmalaya, Jawa Barat ,INA",NaN,Indonesia,244,161 cm,NaN,...,NaN,NaN,1970-05-19,Tasikmalaya,Jawa Barat,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Competed in Olympic Games,Male,Daniil Ruslanovich•Serokhvostov,Daniil Serokhvostov,"4 April 1999 , Barnaul, Altay Kray ,RUS",NaN,ROC,148770,168 cm,NaN,...,Даниил Русланович•Серохвостов,NaN,1999-04-04,Barnaul,Altay Kray,NaN,NaT,NaN,NaN,NaN
145096,Competed in Olympic Games,Female,Kamila Valeryevna•Valiyeva,Kamila Valiyeva,"26 April 2006 , Kazan, Respublika Tatarstan ,RUS",NaN,ROC,148809,160 cm,NaN,...,Камила Валерьевна•Валиева,NaN,2006-04-26,Kazan,Respublika Tatarstan,NaN,NaT,NaN,NaN,NaN
145163,Competed in Olympic Games,Male,Daniel Andrei•Cacina,Daniel Andrei Cacina,"17 October 2001 , Brașov, Brașov ,ROU",NaN,Romania,148880,190 cm,NaN,...,NaN,NaN,2001-10-17,Brașov,Brașov,NaN,NaT,NaN,NaN,NaN
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George Wright,"21 July 1890 , Toronto, Ontario ,CAN","28 January 1973 , Los Angeles, California ,USA",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",...,NaN,NaN,1890-07-21,Toronto,Ontario,NaN,1973-01-28,Los Angeles,California,NaN
145498,Competed in Olympic Games,Male,André•Foussard,André Foussard,"19 May 1899 , Niort, Deux-Sèvres ,FRA","18 March 1986 , Niort, Deux-Sèvres ,FRA",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",...,NaN,NaN,1899-05-19,Niort,Deux-Sèvres,NaN,1986-03-18,None,Deux-Sèvres,NaN

In [228]:
len(df[df["Measurements"].isna()])

37667

In [235]:
measure_pattern = r"(\d+ \w+)"
df[~df["Measurements"].str.match(measure_pattern, na=True)]

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Original name,Name order,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country
37121,Competed in Olympic Games,Male,Guy Oliver•Nickalls,Guy O. Nickalls,"4 April 1899 , Wycombe, England ,GBR","26 April 1974 , London, England ,GBR",Great Britain,37416,"74, 82 kg",NaN,...,NaN,NaN,1899-04-04,None,England,NaN,1974-04-26,London,England,NaN
54695,Competed in Olympic Games,Male,Abdel Manaane•Yahiaoui,Abdel Manaane Yahiaoui,6 December 1966,NaN,Algeria,55089,"68, 70 kg",NaN,...,عبد المنان•يحياوي,NaN,NaT,None,None,NaN,NaT,NaN,NaN,NaN
54705,Competed in Olympic Games,Male,Osvaldo Alberto•Forte,Osvaldo Forte,"1 June 1919 , Buenos Aires, Ciudad Autónoma de...",29 July 2005,Argentina,55099,"81, 82 kg","San Lorenzo, Buenos Aires (ARG)",...,NaN,NaN,1919-06-01,Buenos Aires,Ciudad Autónoma de Buenos Aires,NaN,NaT,None,None,NaN
54706,Competed in Olympic Games,Male,Marcelo Gustavo•Gandolfo López,Marcelo Gandolfo,6 July 1972,NaN,Argentina,55100,"60, 69 kg",NaN,...,NaN,NaN,NaT,None,None,NaN,NaT,NaN,NaN,NaN
54711,Competed in Olympic Games,Male,Gustavo A.•Majauskas Manfredi,Gustavo Majauskas,12 January 1966,NaN,Argentina,55105,"60, 64 kg",NaN,...,NaN,NaN,NaT,None,None,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56640,Competed in Olympic Games,Male,Bakhtiyer•Nurullayev,Bakhtiyer Nurullayev,20 January 1975,NaN,Uzbekistan,57043,"76, 84 kg",NaN,...,Бахтиер•Нуруллаев,NaN,NaT,None,None,NaN,NaT,NaN,NaN,NaN
56873,Competed in Olympic Games,Male,Georges•Colpaert,Georges Colpaert,NaN,NaN,Belgium,57278,92-96 kg,"Verenigde Krachtmeters, Gent (BEL)",...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN
56894,Competed in Olympic Games,Male,"Fredericus Henricus Rosalia ""Frits""•Janssens",Frits Janssens,"14 March 1892 , Berchem, Antwerpen ,BEL","30 March 1965 , Schoten, Antwerpen ,BEL",Belgium,57299,64-67 kg,"WC Verenigde Krachtmeters, Antwerpen (BEL)",...,NaN,NaN,1892-03-14,None,Antwerpen,NaN,1965-03-30,None,Antwerpen,NaN
56908,Competed in Olympic Games,Male,Léon Nicolas•Pottier,Léon Pottier,"8 February 1891 , Stavelot, Liège ,BEL","6 July 1941 , Verviers, Liège ,BEL",Belgium,57313,94-100 kg,"RCA Spa, Spa (BEL)",...,NaN,NaN,1891-02-08,Stavelot,Liège,NaN,1941-07-06,Verviers,Liège,NaN
94009,Competed in Olympic Games,Male,Ofisa•Ofisa,Ofisa Ofisa,"6 April 1974 , Apia, Tuamasaga ,SAM",NaN,Samoa,94768,"76, 85 kg",NaN,...,NaN,NaN,1974-04-06,Apia,Tuamasaga,NaN,NaT,NaN,NaN,NaN

In [237]:
df[["Height_cm", "Weight_kg"]] = df["Measurements"].str.split("/", expand=True)
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country,Height_cm,Weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 , Saint-Jean-de-Luz, Pyrénées-A...",France,1,NaN,NaN,...,1886-12-12,Bordeaux,Gironde,NaN,1960-10-02,Saint-Jean-de-Luz,Pyrénées-Atlantiques,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,1969-04-01,Meulan,Yvelines,NaN,NaT,NaN,NaN,NaN,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN,1994-07-17,Arbonne,Pyrénées-Atlantiques,NaN,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,1895-05-11,Paris VIIIe,Paris,NaN,1978-03-20,None,Monaco,NaN,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 , Paris VIIe, Paris ,FRA",France,5,NaN,"TCP, Paris (FRA)",...,1878-04-17,Wandsworth,England,NaN,1930-07-25,Paris VIIe,Paris,NaN,NaN,NaN

In [239]:
len(df[df["Height_cm"].str.contains("kg", na=False)])

1182

In [242]:
kg_in_height = df["Height_cm"].str.contains("kg", na=False)
kg_in_height

0         False
1         False
2         False
3         False
4         False
          ...
145495    False
145496    False
145497    False
145498    False
145499    False
Name: Height_cm, Length: 145500, dtype: bool

In [243]:
df.loc[kg_in_height, "Weight_kg"] = df[df["Height_cm"].str.contains("kg", na=False)]

In [244]:
df.loc[kg_in_height, "Height_cm"] = None

In [245]:
len(df[df["Height_cm"].str.contains("kg", na=False)])

0

In [ ]:
# dealing wiht the , in the Weight_kg column
df[df["Weight_kg"].str.contains(",", na=False)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country,Height_cm,Weight_kg
54937,Competed in Olympic Games,Male,Ivan Todorov•Veselinov,Ivan Veselinov,"16 November 1926 , Kossovo ,BUL",1996,Bulgaria,55332,"175 cm / 89, 115 kg","Cerveno zname, Asenovgrad (BUL)",...,1926-11-16,Kossovo,BUL,NaN,NaT,None,None,NaN,175 cm,"89, 115 kg"
55730,Competed in Olympic Games • Other,Male,Carlo Pietro•Galimberti,Carlo Galimberti,"2 July 1894 , Rosario, Santa Fe ,ARG","10 August 1939 , Milano, Milano ,ITA",Italy,56126,"167 cm / 74, 75 kg","G.S. ""C. Galimberti"" Vigili del Fuoco, Milano ...",...,1894-07-02,Rosario,Santa Fe,NaN,1939-08-10,Milano,Milano,NaN,167 cm,"74, 75 kg"
55748,Competed in Olympic Games,Male,Gastone Edgardo•Pierini,Gastone Pierini,"27 September 1899 , Ancona, Ancona ,ITA","17 September 1967 , São Bernardo do Campo, São...",Italy,56144,"167 cm / 66, 67 kg",NaN,...,1899-09-27,None,Ancona,NaN,1967-09-17,São Bernardo do Campo,São Paulo,NaN,167 cm,"66, 67 kg"
55962,Competed in Olympic Games,Male,Rafael Armando•Rueda García,Armando Rueda,"19 February 1929 , Torreón, Coahuila ,MEX",27 November 2018,Mexico,56359,"183 cm / 74, 81 kg",NaN,...,1929-02-19,Torreón,Coahuila,NaN,NaT,None,None,NaN,183 cm,"74, 81 kg"
56060,Competed in Olympic Games • Other,Male,Muhammad Malik•Arshad,Malik Arshad,18 May 1948,"16 February 2021 , Gujranwala, Punjab ,PAK",Pakistan,56458,"171 cm / 74, 75 kg",NaN,...,NaT,None,None,NaN,2021-02-16,Gujranwala,Punjab,NaN,171 cm,"74, 75 kg"

In [288]:
coma_in_weight = df["Weight_kg"].str.contains(",", na=False)
coma_in_weight.head()

0    False
1    False
2    False
3    False
4    False
Name: Weight_kg, dtype: bool

In [ ]:
df.loc[coma_in_weight, "Weight_kg"] = df.loc[coma_in_weight, "Weight_kg"].str.extract(r",\s*(.+)", expand=False)

In [292]:
df[df["Weight_kg"].str.contains(",", na=False)].head()

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country, Height_cm, Weight_kg]
Index: []

[0 rows x 26 columns]

In [ ]:
# dealing wiht the - in the Weight_kg column
df[df["Weight_kg"].str.contains("-", na=False)].head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country,Height_cm,Weight_kg
432,Competed in Olympic Games,Female,Minna Kaarina•Heinonen (-Koivisto),Minna Heinonen,"26 August 1967 , Harjavalta, Satakunta ,FIN",NaN,Finland,433,173 cm / 64-66 kg,Harjavallan Jousiampujat,...,1967-08-26,Harjavalta,Satakunta,NaN,NaT,NaN,NaN,NaN,173 cm,64-66 kg
435,Competed in Olympic Games,Female,Jutta Anneli•Poikolainen (Vähäoja-),Jutta Poikolainen,"15 March 1963 , Tampere, Pirkanmaa ,FIN",NaN,Finland,436,176 cm / 63-65 kg,"Amarco, Hyvinkää (FIN)",...,1963-03-15,Tampere,Pirkanmaa,NaN,NaT,NaN,NaN,NaN,176 cm,63-65 kg
437,Competed in Olympic Games,Male,Ismo Kalevi•Falck,Ismo Falck,"22 August 1966 , Paltamo, Kainuu ,FIN",NaN,Finland,438,172 cm / 67-74 kg,"Suomussalmen Vastus, Suomussalmi (FIN)",...,1966-08-22,Paltamo,Kainuu,NaN,NaT,NaN,NaN,NaN,172 cm,67-74 kg
440,Competed in Olympic Games,Male,Kauko Markus•Laasonen,Kauko Laasonen,"8 January 1951 , Kesälahti, Pohjois-Karjala ,FIN",NaN,Finland,441,178 cm / 73-75 kg,"Porin Jousiampujat, Pori (FIN)",...,1951-01-08,Kesälahti,Pohjois-Karjala,NaN,NaT,NaN,NaN,NaN,178 cm,73-75 kg
441,Competed in Olympic Games,Male,Kyösti Kalevi•Laasonen,Kyösti Laasonen,"27 September 1945 , Kitee, Pohjois-Karjala ,FIN",NaN,Finland,442,173 cm / 63-65 kg,"Porin Jousiampujat, Pori (FIN)",...,1945-09-27,Kitee,Pohjois-Karjala,NaN,NaT,NaN,NaN,NaN,173 cm,63-65 kg

In [294]:
dash_in_weight = df["Weight_kg"].str.contains("-", na=False)
dash_in_weight.head()

0    False
1    False
2    False
3    False
4    False
Name: Weight_kg, dtype: bool

In [295]:
df.loc[dash_in_weight, "Weight_kg"] = df.loc[dash_in_weight, "Weight_kg"].str.extract(r",\s*(.+)", expand=False)

In [296]:
df[df["Weight_kg"].str.contains("-", na=False)].head()

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country, Height_cm, Weight_kg]
Index: []

[0 rows x 26 columns]

In [316]:
measure_pattern = r"(\d+)"
df[df["Weight_kg"].str.match(measure_pattern, na=False)]
df[~df["Height_cm"].str.match(measure_pattern, na=True)]

Empty DataFrame
Columns: [Roles, Sex, Full name, Name, Born, Died, NOC, athlete_id, Measurements, Affiliations, Nick/petnames, Title(s), Other names, Nationality, Original name, Name order, Born date, Born city, Born region, Born country, Died date, Died city, Died region, Died country, Height_cm, Weight_kg]
Index: []

[0 rows x 26 columns]

In [ ]:
# removing the cm and kg from the columns
df["Height_cm"] = df["Height_cm"].str.replace("cm", "")
df["Weight_kg"] = df["Weight_kg"].str.replace("kg", "")

In [298]:
df.head()

,Roles,Sex,Full name,Name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Born date,Born city,Born region,Born country,Died date,Died city,Died region,Died country,Height_cm,Weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François Blanchy,"12 December 1886 , Bordeaux, Gironde ,FRA","2 October 1960 , Saint-Jean-de-Luz, Pyrénées-A...",France,1,NaN,NaN,...,1886-12-12,Bordeaux,Gironde,NaN,1960-10-02,Saint-Jean-de-Luz,Pyrénées-Atlantiques,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud Boetsch,"1 April 1969 , Meulan, Yvelines ,FRA",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,1969-04-01,Meulan,Yvelines,NaN,NaT,NaN,NaN,NaN,183,76
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean Borotra,"13 August 1898 , Biarritz, Pyrénées-Atlantique...","17 July 1994 , Arbonne, Pyrénées-Atlantiques ,FRA",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,1898-08-13,Biarritz,Pyrénées-Atlantiques,NaN,1994-07-17,Arbonne,Pyrénées-Atlantiques,NaN,183,76
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques Brugnon,"11 May 1895 , Paris VIIIe, Paris ,FRA","20 March 1978 , Monaco, Monaco ,MON",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,1895-05-11,Paris VIIIe,Paris,NaN,1978-03-20,None,Monaco,NaN,168,64
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert Canet,"17 April 1878 , Wandsworth, England ,GBR","25 July 1930 , Paris VIIe, Paris ,FRA",France,5,NaN,"TCP, Paris (FRA)",...,1878-04-17,Wandsworth,England,NaN,1930-07-25,Paris VIIe,Paris,NaN,NaN,NaN

### Final file

In [ ]:
columns_needed = ["athlete_id", "Name", "Height_cm", "Weight_kg", "Born date", "Born city", "Born region", "Born country", "Died date", "Died city", "Died region", "Died country"]